services:
  restaurent-api-db:
    container_name: restaurent-api-container
    image: postgres:14.2
    restart: always
    environment:
      POSTGRES_DB: "restaurent_db"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - vol-restaurent-api-db:/var/lib/postgresql/data

volumes:
  vol-restaurent-api-db:
